//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidAssignment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Employee name can't be blank")]
        [Display(Name = "Please Enter the Employee Name")]
        [MaxLength(50, ErrorMessage = "Not more than 50 alphabets")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Date can't be blank")]
        [Display(Name = "Joining Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> JoiningDate { get; set; }

        [Required(ErrorMessage = "Salary can't be blank")]
        [Display(Name = "Salary")]
        [Range(1000, 60000, ErrorMessage = "Salary range can be between 1000 to 60000")]
        public Nullable<double> Salary { get; set; }

        [Required(ErrorMessage = "Department Name can't be blank")]
        [Display(Name = "Department")]
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
